# Generated by Django 5.0 on 2023-12-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_file',
            field=models.FileField(blank=True, null=True, upload_to='quiz/'),
        ),
    ]
